USE Proyecto_MAD;
GO

---STORED PROCEDURES COMPRAS_FORMA_DE_PAGOyENVIO
---Procesos COMPRAS_FORMA_DE_PAGOyENVIO



CREATE PROC PR_FormaPago_ComboBox
		AS
		SELECT Id_Forma_De_Pago,Forma_De_Pago FROM FORMA_DE_PAGO
	GO

	CREATE PROC PR_FormaEnvio_ComboBox
		AS
		SELECT Id_Forma_De_Envio,Forma_De_Envio FROM FORMA_DE_ENVIO
	GO
